import { createContext, useContext, useState, useEffect } from 'react';

const dictionary = {
  zh: {
    // 共用
    appName: 'YY 手帳',
    logout: '登出',
    loading: '載入中…',
    save: '儲存',
    cancel: '取消',
    reselect: '重新選擇',
    mode_add: '新增',
    mode_edit: '編輯',
    mode_delete: '刪除',
    mode_transfer: '轉帳',
    type_expense: '支出',
    type_income: '收入',
    type_general: '通用',

    // 導覽 / 概覽
    nav_home: '首頁',
    nav_transactions: '記帳',
    nav_calendar: '行事曆',
    nav_accounts: '帳戶',
    nav_recurring: '循環',
    nav_ledger: '記帳',
    nav_announcements: '公告',
    nav_community: '社群',
    nav_settings: '設定',
    sub_recurring: '循環',
    sub_recurring_events: '循環行程',
    ann_empty: '目前沒有公告',
    community_placeholder: '社群功能開發中,敬請期待',
    settings_account: '帳戶資訊',
    settings_notifications: '通知設定',
    home_ledger_subtitle: '帳務 · 帳戶 · 循環',
    home_calendar_subtitle: '行事曆 · 循環行程',
    home_announcements_subtitle: '最新系統公告',
    home_community_subtitle: '功能開發中',
    home_settings_subtitle: '帳戶與通知設定',
    overview: '概覽',
    month_expense: '本月支出',
    month_income: '本月收入',
    total_balance: '總餘額',
    today_events: '今日行程',
    no_events_today: '今天沒有安排的行程',

    // 記帳
    tx_pageTitle: '記帳',
    tx_view_list: '列表',
    tx_view_calendar: '日曆',
    tx_amount: '金額',
    tx_note_placeholder: '說明(選填,例如:跟同事聚餐)',
    tx_account_placeholder: '選擇帳戶(選填)',
    tx_no_account: '不指定帳戶',
    tx_category_placeholder: '選擇分類(選填)',
    tx_no_category: '不指定分類',
    tx_manage_categories: '管理分類',
    tx_save_edit: '儲存修改',
    tx_add_record: '新增紀錄',
    tx_pick_edit: '請從下方列表點選要編輯的紀錄',
    tx_pick_delete: '請從下方列表點選要刪除的紀錄',
    tx_confirm_delete_title: '確定要刪除這筆紀錄嗎?',
    tx_confirm_delete: '確認刪除',
    tx_no_records: '還沒有任何紀錄',
    tx_no_note: '（無說明）',
    tx_editing: '正在編輯這筆紀錄',
    tx_unspecified_account: '未指定帳戶',
    tx_transfer_from: '從哪個帳戶轉出',
    tx_transfer_to: '轉入哪個帳戶',
    tx_transfer_amount: '轉帳金額',
    tx_confirm_transfer: '確認轉帳',
    tx_transfer_error_same: '轉出與轉入帳戶不能相同',
    tx_transfer_error_fail: '轉帳失敗,請確認金額與帳戶是否正確',
    tx_search_placeholder: '搜尋說明或分類…',

    // 帳戶
    acc_pageTitle: '帳戶管理',
    acc_new_name_placeholder: '新帳戶名稱',
    acc_add: '新增',
    acc_no_accounts: '還沒有任何帳戶,先新增一個吧',
    acc_pick_rename: '請點選要重新命名的帳戶',
    acc_pick_delete: '請點選要刪除的帳戶',
    acc_confirm_delete_prefix: '確定要刪除「',
    acc_confirm_delete_suffix: '」嗎?',
    acc_delete_note: '過去這個帳戶的交易紀錄仍會保留,只是不再顯示所屬帳戶。',
    acc_update_failed: '更新失敗',
    acc_delete_failed: '刪除失敗',

    // 行事曆
    cal_pageTitle: '行事曆',
    cal_select_date_prompt: '請先在上方月曆點選一個日期',
    cal_events_of_day_suffix: ' 的行程',
    cal_no_events_this_day: '這天沒有任何行程',
    cal_title_placeholder: '事件標題',
    cal_category_placeholder: '分類(選填,如:工作/個人)',
    cal_add_event: '新增事件',
    cal_editing: '正在編輯這筆行程',
    cal_pick_edit: '請點選要編輯的行程',
    cal_pick_delete: '請點選要刪除的行程',
    cal_confirm_delete_title: '確定要刪除這筆行程嗎?',
    cal_weekdays: ['日', '一', '二', '三', '四', '五', '六'],
    cal_search_placeholder: '搜尋行程標題或分類…',
    cal_no_search_results: '找不到符合的行程',

    // 循環提醒
    rec_pageTitle: '循環記帳/行程提醒',
    rec_enable_push: '啟用推播通知',
    rec_enabling: '設定中…',
    rec_push_enabled: '✓ 推播通知已啟用',
    rec_push_failed: '未能啟用推播(可能是瀏覽器拒絕通知權限,或尚未設定 Firebase)',
    rec_kind_expense: '循環支出',
    rec_kind_income: '循環收入',
    rec_kind_event: '循環行程',
    rec_title_placeholder: '項目名稱',
    rec_amount_placeholder: '金額(選填)',
    rec_day_of_month_label: '每月第幾天',
    rec_reminder_method_label: '提醒方式',
    rec_reminder_push: '推播通知',
    rec_reminder_in_app: '僅 APP 內顯示',
    rec_reminder_both: '兩者皆要',
    rec_add: '新增循環項目',
    rec_no_items: '還沒有循環項目',
    rec_active: '啟用中',
    rec_inactive: '已停用',
    rec_pick_edit: '請從上方列表點選要編輯的項目',
    rec_pick_delete: '請從上方列表點選要刪除的項目',
    rec_confirm_delete_title: '確定要刪除這個循環項目嗎?',
    rec_editing: '正在編輯這個循環項目',
    rec_monthly_prefix: '每月 ',
    rec_monthly_suffix: ' 號',
    rec_weekly: '每週',
    rec_next: '下次:',

    // 分類管理
    cat_pageTitle: '分類管理',
    cat_back_to_transactions: '回記帳',
    cat_new_name_placeholder: '新分類名稱',
    cat_no_categories: '還沒有任何分類,新增第一個吧',
    cat_rename: '重新命名',
    cat_confirm_delete_prefix: '確定刪除「',
    cat_confirm_delete_suffix: '」?',
    cat_error_create: '新增失敗,可能是分類名稱重複',
    cat_error_rename: '重新命名失敗,可能是名稱重複',
    cat_error_delete: '刪除失敗',
    cat_error_load: '無法載入分類清單',
  },
  en: {
    appName: 'YY Journal',
    logout: 'Logout',
    loading: 'Loading…',
    save: 'Save',
    cancel: 'Cancel',
    reselect: 'Reselect',
    mode_add: 'Add',
    mode_edit: 'Edit',
    mode_delete: 'Delete',
    mode_transfer: 'Transfer',
    type_expense: 'Expense',
    type_income: 'Income',
    type_general: 'General',

    nav_home: 'Home',
    nav_transactions: 'Ledger',
    nav_calendar: 'Calendar',
    nav_accounts: 'Accounts',
    nav_recurring: 'Recurring',
    nav_ledger: 'Ledger',
    nav_announcements: 'Announcements',
    nav_community: 'Community',
    nav_settings: 'Settings',
    sub_recurring: 'Recurring',
    sub_recurring_events: 'Recurring Events',
    ann_empty: 'No announcements yet',
    community_placeholder: 'Community feature coming soon',
    settings_account: 'Account',
    settings_notifications: 'Notifications',
    home_ledger_subtitle: 'Transactions · Accounts · Recurring',
    home_calendar_subtitle: 'Calendar · Recurring events',
    home_announcements_subtitle: 'Latest announcements',
    home_community_subtitle: 'Coming soon',
    home_settings_subtitle: 'Account & notifications',
    overview: 'Overview',
    month_expense: 'This Month Spending',
    month_income: 'This Month Income',
    total_balance: 'Total Balance',
    today_events: "Today's Events",
    no_events_today: 'No events scheduled today',

    tx_pageTitle: 'Ledger',
    tx_view_list: 'List',
    tx_view_calendar: 'Calendar',
    tx_amount: 'Amount',
    tx_note_placeholder: 'Note (optional, e.g. Dinner with colleagues)',
    tx_account_placeholder: 'Select account (optional)',
    tx_no_account: 'No account',
    tx_category_placeholder: 'Select category (optional)',
    tx_no_category: 'No category',
    tx_manage_categories: 'Manage categories',
    tx_save_edit: 'Save changes',
    tx_add_record: 'Add record',
    tx_pick_edit: 'Select a record below to edit',
    tx_pick_delete: 'Select a record below to delete',
    tx_confirm_delete_title: 'Delete this record?',
    tx_confirm_delete: 'Confirm delete',
    tx_no_records: 'No records yet',
    tx_no_note: '(No note)',
    tx_editing: 'Editing this record',
    tx_unspecified_account: 'No account',
    tx_transfer_from: 'Transfer from',
    tx_transfer_to: 'Transfer to',
    tx_transfer_amount: 'Transfer amount',
    tx_confirm_transfer: 'Confirm transfer',
    tx_transfer_error_same: 'Source and destination accounts must differ',
    tx_transfer_error_fail: 'Transfer failed, please check amount and accounts',
    tx_search_placeholder: 'Search note or category…',

    acc_pageTitle: 'Accounts',
    acc_new_name_placeholder: 'New account name',
    acc_add: 'Add',
    acc_no_accounts: 'No accounts yet — add one to get started',
    acc_pick_rename: 'Select an account to rename',
    acc_pick_delete: 'Select an account to delete',
    acc_confirm_delete_prefix: 'Delete "',
    acc_confirm_delete_suffix: '"?',
    acc_delete_note: "Past transactions for this account will be kept, but will no longer show an associated account.",
    acc_update_failed: 'Update failed',
    acc_delete_failed: 'Delete failed',

    cal_pageTitle: 'Calendar',
    cal_select_date_prompt: 'Please select a date on the calendar above',
    cal_events_of_day_suffix: "'s events",
    cal_no_events_this_day: 'No events this day',
    cal_title_placeholder: 'Event title',
    cal_category_placeholder: 'Category (optional, e.g. Work/Personal)',
    cal_add_event: 'Add event',
    cal_editing: 'Editing this event',
    cal_pick_edit: 'Select an event to edit',
    cal_pick_delete: 'Select an event to delete',
    cal_confirm_delete_title: 'Delete this event?',
    cal_weekdays: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
    cal_search_placeholder: 'Search event title or category…',
    cal_no_search_results: 'No matching events found',

    rec_pageTitle: 'Recurring Ledger & Reminders',
    rec_enable_push: 'Enable push notifications',
    rec_enabling: 'Setting up…',
    rec_push_enabled: '✓ Push notifications enabled',
    rec_push_failed: "Couldn't enable push (browser may have blocked permission, or Firebase isn't configured)",
    rec_kind_expense: 'Recurring expense',
    rec_kind_income: 'Recurring income',
    rec_kind_event: 'Recurring event',
    rec_title_placeholder: 'Item name',
    rec_amount_placeholder: 'Amount (optional)',
    rec_day_of_month_label: 'Day of month',
    rec_reminder_method_label: 'Reminder method',
    rec_reminder_push: 'Push notification',
    rec_reminder_in_app: 'In-app only',
    rec_reminder_both: 'Both',
    rec_add: 'Add recurring item',
    rec_no_items: 'No recurring items yet',
    rec_active: 'Active',
    rec_inactive: 'Inactive',
    rec_pick_edit: 'Select an item above to edit',
    rec_pick_delete: 'Select an item above to delete',
    rec_confirm_delete_title: 'Delete this recurring item?',
    rec_editing: 'Editing this recurring item',
    rec_monthly_prefix: 'Day ',
    rec_monthly_suffix: ' of each month',
    rec_weekly: 'Weekly',
    rec_next: 'Next:',

    cat_pageTitle: 'Categories',
    cat_back_to_transactions: 'Back to ledger',
    cat_new_name_placeholder: 'New category name',
    cat_no_categories: 'No categories yet — add your first one',
    cat_rename: 'Rename',
    cat_confirm_delete_prefix: 'Delete "',
    cat_confirm_delete_suffix: '"?',
    cat_error_create: 'Failed to add — name may already exist',
    cat_error_rename: 'Rename failed — name may already exist',
    cat_error_delete: 'Delete failed',
    cat_error_load: 'Failed to load categories',
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem('language') || 'zh');

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  function toggleLanguage() {
    setLanguage((prev) => (prev === 'zh' ? 'en' : 'zh'));
  }

  function t(key) {
    return dictionary[language]?.[key] ?? dictionary.zh[key] ?? key;
  }

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}
